@startuml StandardDoc_Blocks
/'
Diagram:        StandardDoc_StandardDocument
DateCreate:     22/08/2018
Description:    Metanorma StandardDocument ("StanDoc") is a family of document models that forms the basis of Metanorma IsoDoc, which is used to represent
                ISO Standards and similarly structured standards. It itself is an instantiation of BasicDocument (BasicDoc)
                It is one of the document models that Selagraph operates on.
                Metanorma StandardDocument itself is a document model can form the basis of multiple standard document types, including:

                - ISO Standards
                - CSD Standards
                - Chinese Standards (GB and family)

                The Relaton Bibliography UML models used within these models are located here: Relaton BibModels

Hystory of changes:
> DD/MM/YYYY
    - 31/10/2019: example/role
    - 10/01/2020: StandardNoteBlock
    - 14/01/2020: ReferenceToTerm
    - 04/02/2020: ReferenceToTerm
    - 20/03/2020: Table
    - 15/06/2020: number attribute overriding autonumbering
    - 16/06/2020: keep-with-next, keep-lines-together
    - 17/06/2020: note/@type
    - 07/09/2020: add to note contents
    - 09/09/2020: amend block
    - 06/11/2020: dl/@key
'/

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class BasicDocument <<BasicDocument>> {

}

class NoteBlock <<BasicDocument>> {
}

class FigureBlock <<BasicDocument>> {
}

class SourcecodeBlock <<BasicDocument>> {
}

class FormulaBlock <<BasicDocument>> {
}

class ExampleBlock <<BasicDocument>> {
}

class ParagraphBlock <<BasicDocument>> {
}

class QuoteBlock <<BasicDocument>> {
}

class AdmonitionBlock <<BasicDocument>> {
}

class UnorderedList <<BasicDocument>> {
}

class DefinitionList <<BasicDocument>> {
}

class StandardNoteBlock {
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
    +number: String[0..1]
    +subsequence: String[0..1]
    +unnumbered: Boolean[0..1]
    +type: String[0..1]
    +ul: UnorderedList[0..*]
    +ol: OrderedList[0..*]
    +dl: DefinitionList[0..*]
    +formula: FormulaBlock[0..*]
    +sourcecode: SourcecodeBlock[0..*]
    +quotes: QuoteBlock[0..*]
}

class UnorderedList <<BasicDocument>> {
}

class StandardUnorderedList {
    +listitem: UnorderedCheckableListItem[0..*]
}

class ListItem <<BasicDocument>> {
}

class UnorderedCheckableListItem {
    +checkbox: Boolean
    +checkedcheckbox: Boolean
}

class TableBlock <<BasicDocument>> {
}

class StandardTableBlock {
    +width: String[0..1]
    +number: String[0..1]
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardFigureBlock {
    +number: String[0..1]
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardSourcecodeBlock {
    +number: String[0..1]
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardFormulaBlock {
    +number: String[0..1]
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardExampleBlock {
    +number: String[0..1]
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardParagraphBlock {
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardQuoteBlock {
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardAdmonitionBlock {
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardUnorderedList {
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
}

class StandardDefinitionList {
    +keep-lines-together: Boolean[0..1],
    +keep-with-next: Boolean[0..1],
    +key: Boolean[0..1]
}

class AmendBlock {
    +change: ChangeType,
    +bibLocality: BibItemLocality[0..*],
    +path: String[0..1],
    +path_end: String[0..1],
    +name: String[0..1],
    +description: BasicBlock[0..*],
    +autonumber: AutoNumber[0..*],
    +newcontent: BasicBlock[0..*]
}

class AutoNumber {
    +type: ElementName,
    +value: String
}

class BibItemLocality <<Relaton>> {
}

enum ChangeType <<enumeration>>{
    add
    modify
    delete
}

enum ElementName <<enumeration>>{
    requirement
    recommendation
    permission
    table
    figure
    admonition
    formula
    sourcecode
    example
    note
}

'******* NOTES ********************************************************


'******* CLASS RELATIONS **********************************************
BasicDocument <-- NoteBlock
BasicDocument <-- UnorderedList
BasicDocument <-- ListItem
BasicDocument <-- TableBlock
NoteBlock <|-- StandardNoteBlock
UnorderedList <|-- StandardUnorderedList
ListItem <|-- UnorderedCheckableListItem
TableBlock <|-- StandardTableBlock
BasicDocument <-- FigureBlock
FigureBlock <|-- StandardFigureBlock
BasicDocument <-- SourcecodeBlock
SourcecodeBlock <|-- StandardSourcecodeBlock
BasicDocument <-- FormulaBlock
FormulaBlock <|-- StandardFormulaBlock
BasicDocument <-- ExampleBlock
ExampleBlock <|-- StandardExampleBlock
BasicDocument <-- ParagraphBlock
ParagraphBlock <|-- StandardParagraphBlock
BasicDocument <-- QuoteBlock
QuoteBlock <|-- StandardQuoteBlock
BasicDocument <-- AdmonitionBlock
AdmonitionBlock <|-- StandardAdmonitionBlock
BasicDocument <-- UnorderedList
UnorderedList <|-- StandardUnorderedList
BasicDocument <-- DefinitionList
DefinitionList <|-- StandardDefinitionList
AmendBlock <-- ChangeType
AmendBlock <-- AutoNumber
AmendBlock <-- BibItemLocality
AmendBlock <-- ElementName

@enduml
