@startuml StandardDoc_Block
/'
Diagram:        StandardDoc_StandardDocument
DateCreate:     22/08/2018
Description:    Metanorma StandardDocument ("StanDoc") is a family of document models that forms the basis of Metanorma IsoDoc, which is used to represent
                ISO Standards and similarly structured standards. It itself is an instantiation of BasicDocument (BasicDoc)
                It is one of the document models that Selagraph operates on.
                Metanorma StandardDocument itself is a document model can form the basis of multiple standard document types, including:

                - ISO Standards
                - CSD Standards
                - Chinese Standards (GB and family)

                The Relaton Bibliography UML models used within these models are located here: Relaton BibModels

Hystory of changes:
> DD/MM/YYYY
    - 31/10/2019: example/role
    - 10/01/2020: StandardNoteBlock
    - 14/01/2020: ReferenceToTerm
    - 04/02/2020: ReferenceToTerm
    - 04/02/2020: ReferenceToTerm
'/

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class BasicDocument <<BasicDocument>> {

}

class NoteBlock <<BasicDocument>> {
}

class StandardNoteBlock {
    +ul: UnorderedList[0..*]
    +ol: OrderedList[0..*]
    +dl: DefinitionList[0..*]
    +formula: FormulaBlock[0..*]
}

class UnorderedList <<BasicDocument>> {
}

class StandardUnorderedList {
    +listitem: UnorderedCheckableListItem[0..*]
}

class ListItem <<BasicDocument>> {
}

class UnorderedCheckableListItem {
    +checkbox: Boolean
    +checkedcheckbox: Boolean
}


'******* NOTES ********************************************************


'******* CLASS RELATIONS **********************************************
BasicDocument <-- NoteBlock
BasicDocument <-- UnorderedList
BasicDocument <-- ListItem
NoteBlock <|-- StandardNoteBlock 
UnorderedList <|-- StandardUnorderedList
ListItem <|-- UnorderedCheckableListItem

@enduml
